sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
os:
  - linux

#env:
#  - MOZ_HEADLESS=1

addons:
  firefox: latest
  xserver: latest

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle


