sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
os:
  - linux

env:
  - MOZ_HEADLESS=1

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y dbus-x11

addons:
  firefox: latest
  xserver: latest

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle


